name: Reddit Lead Finder - Scheduled Scan

on:
  schedule:
    # Runs daily at 9 AM UTC (adjust as needed)
    - cron: '0 9 * * *'
  workflow_dispatch: # Allows manual triggering

jobs:
  scan-reddit:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
    
    - name: Run Reddit Lead Finder
      env:
        REDDIT_CLIENT_ID: ${{ secrets.REDDIT_CLIENT_ID }}
        REDDIT_CLIENT_SECRET: ${{ secrets.REDDIT_CLIENT_SECRET }}
        REDDIT_USER_AGENT: "TradingWizard Lead Finder v1.0"
      run: |
        python main.py
    
    - name: Upload results
      uses: actions/upload-artifact@v3
      with:
        name: reddit-leads-${{ github.run_number }}
        path: leads.json
        retention-days: 30
    
    - name: Commit results to repository (optional)
      if: github.event_name == 'schedule'
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add leads.json
        git commit -m "Update leads: $(date +'%Y-%m-%d %H:%M:%S UTC')" || echo "No changes to commit"
        git push || echo "Nothing to push"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
